// @ts-check
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';
import boundaries from 'eslint-plugin-boundaries';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  // Base Next.js rules (includes typescript-eslint, react, react-hooks, jsx-a11y)
  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  // eslint-plugin-boundaries configuration
  {
    plugins: {
      boundaries,
    },
    settings: {
      'boundaries/elements': [
        { type: 'atomic', pattern: 'src/components/atomic/*' },
        { type: 'composite', pattern: 'src/components/composite/*' },
        { type: 'decoration', pattern: 'src/components/decoration/*' },
        { type: 'motion', pattern: 'src/components/motion/*' },
        { type: 'page', pattern: 'src/components/page/*' },
        { type: 'data', pattern: 'src/data/*' },
        { type: 'lib', pattern: 'src/lib/*' },
        { type: 'hooks', pattern: 'src/hooks/*' },
        { type: 'app', pattern: 'src/app/**' },
        { type: 'types', pattern: 'src/types/*' },
      ],
      'boundaries/ignore': ['**/*.test.*', '**/*.spec.*', 'scripts/**'],
    },
    rules: {
      // Layer direction: atomic MUST NOT import from composite, page, motion, decoration
      'boundaries/element-types': [
        'error',
        {
          default: 'allow',
          rules: [
            {
              from: 'atomic',
              disallow: ['composite', 'page', 'motion', 'decoration'],
              message:
                'atomic/ must not import from composite/, page/, motion/, or decoration/. (Boundary rule 1)',
            },
            {
              from: 'composite',
              allow: ['atomic', 'decoration', 'lib', 'hooks', 'types'],
              disallow: ['page', 'motion'],
              message:
                'composite/ may only import atomic/, decoration/, lib/, hooks/, and types/. (Boundary rule 1)',
            },
            {
              from: 'page',
              allow: ['atomic', 'composite', 'decoration', 'motion', 'data', 'lib', 'hooks', 'types'],
              message: 'page/ may import all component layers + data/ + lib/. (Boundary rule 1)',
            },
            {
              // motion/ and client-component files must not import from data/
              from: 'motion',
              disallow: ['data'],
              message:
                'motion/ components must not import from src/data/ — data flows inward via props. (Boundary rule 3)',
            },
            {
              from: 'app',
              allow: ['page', 'data', 'lib', 'hooks', 'types'],
              message:
                'app/**/page.tsx may only import page/, data/, lib/, hooks/, and types/. (Boundary rule 1)',
            },
          ],
        },
      ],
    },
  },

  // Project-wide rules
  {
    rules: {
      // Accessibility requirements
      'jsx-a11y/alt-text': 'error',
      'jsx-a11y/label-has-associated-control': 'error',

      // Ban bare `motion` named export from framer-motion (force `m` only for tree-shaking)
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'framer-motion',
              importNames: ['motion'],
              message:
                'Do not import the bare `motion` export from framer-motion. Use `m` with `LazyMotion` instead for tree-shaking. See architecture § 10.',
            },
          ],
          patterns: [
            {
              group: ['next/image'],
              message:
                'Import next/image only inside src/components/atomic/Image.tsx. Use the <Image> atomic component everywhere else. (Boundary rule — next/image is the ONE allowed import site.)',
            },
          ],
        },
      ],
    },
  },

  // Allow next/image only inside the atomic Image component
  {
    files: ['src/components/atomic/Image.tsx'],
    rules: {
      'no-restricted-imports': 'off',
    },
  },

  // Ignore patterns
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      // Inherited assets are read-only vendored files — not part of the rebuild source
      '_inherited_assets/**',
      // Auto-generated by Next.js — not lintable source
      'next-env.d.ts',
    ],
  },
];

export default eslintConfig;
